### ISSUE TITLE
geography (Point) type translated to String instead of a matching underlying type

### ISSUE THREAD

**Issue by LucasVanDongen** [apollographql/iOSCodegenTemplate#1]
I have a `.graphql` file in my Xcode project that looks a bit like this:

```
query MyQuery {
	myData {
		id
		created_at
		title
		location
	}
}
```

When run the same query with the same token etcetera in Hasura I see this:

```
{
  "data": {
    "myData": [
      {
        "id": "d042d3b9-ce3a-4d94-bc57-653fc204b700",
        "created_at": "2021-01-18T18:02:22.074663+00:00",
        "title": "I'm a title",
        "location": null
      },
      {
        "id": "d404fef0-feb6-4964-9ed5-60e726251c01",
        "created_at": "2021-01-18T18:02:22.074663+00:00",   
        "title": "I'm a title",  
        "location": {
          "type": "Point",
          "crs": {
            "type": "name",
            "properties": {
              "name": "urn:ogc:def:crs:EPSG::4326"
            }
          },
          "coordinates": [
            -0.06,
            27
          ]
        }
      },
      ... etcetera ...
    ]
  }
}
```

However the generated data type for that column in `API.swift` is `GraphQLField("location", type: .scalar(String.self))` which gives me a problem at run-time when it tries to translate the actual value (I thought it actually was `[String: Any]` but not 100% sure anymore).

I tried throwing away `schema.json` and other automatically generated files to see if everything was generated back from the server and it did. I think `schema.json` looks OK but I'm not super familiar with it's format. So it looks like the conversion to a Swift type to the field is where it failed.

**Comment by designatednerd** [comment]
Are you using `passthroughCustomScalars`? This is what passes through the types rather than using the underlying type. Please see [our docs on this](https://www.apollographql.com/docs/ios/fetching-queries/#notes-on-working-with-custom-scalars). 

Also, in the future, please open issues on the [main iOS repo](https://github.com/apollographql/apollo-ios), this is just for the scripting template itself. I'm gonna close this out, if you've got follow ups, please open a new issue on the main repo. Thanks!
