### ISSUE TITLE
Codegen not updating input type

### ISSUE THREAD

**Issue by janremes** [apollographql/iOSCodegenTemplate#10]
Hi we are having issues with new swift scripting codegen.
We have a query like this:
```
query ListData($input: ListDataInput!) {
      listData(input: $input) {
        ...DataFragment
      }
}
```

If there is a change in `ListDataInput` parameters in schema. `schema.graphql` is updated but no new API.swift is generated.

We are using Xcode 13, please let me know if you need more info.

**Comment by designatednerd** [comment]
Hm, this is still using the old engine under the hood for now so it would be weird if it's scripting only. 

Can you share the code you're using to set up the codegen? 

My other suggestion is to check and see what happens if you delete `API.swift` - is the same file generated without the updates or is nothing generated? If it's the same file, you may not be pointing where you think you are in terms of the schema file. If it's nothing, it's worth taking a look at the output of your build to see if there are any error messages that are for some reason being ignored.

**Comment by janremes** [comment]
@designatednerd Hi thanks for your response. Deleting API.swift helped. So I think it could be related to Xcode 13 build issues. I added API.swift to output files in build phase. Maybe it will help. Anyway, thanks for your response!

**Comment by designatednerd** [comment]
Great, thanks for letting us know!
