### ISSUE TITLE
ApolloCodegenLib/IR+EntitySelectionTree.swift:192: Fatal error

### ISSUE THREAD

**Issue by iAmericanBoy** [apollographql/iOSCodegenTemplate#21]
Good morning, 
I'm trying to see if I can get the new Swift Code gen to work with our work project and I think its generating most of our files properly but the codegen keeps on erroring out with:
```
ApolloCodegenLib/IR+EntitySelectionTree.swift:192: Fatal error
```
For now I'm assuming user error since I probably dont have the configuration set up correctly but based on that fatal error is there anything obvious that I'm doing wrong?

**Comment by calvincestari** [comment]
Hi 👋🏻 - there's almost no configuration that goes into the IR-building stage of codegen so it looks like this could be a valid build error. Really difficult to diagnose since we're not including any details there either. I'll look at getting a message into that error but would you be able to tell me what the values of `child` and `scope` are?

**Comment by calvincestari** [comment]
@iAmericanBoy I've [replicated this issue](https://github.com/apollographql/apollo-ios/issues/2434) over in apollo-ios where the real problem, if any, will be. I'm going to close this one and let's continue the conversation in that issue rather.

**Comment by iAmericanBoy** [comment]
Sounds good thank you
